In [5]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import scipy
%matplotlib inline
from sklearn.neighbors import KNeighborsClassifier
from scipy import stats

In [6]:
df= pd.read_csv('Admission_Predict.csv')


In [7]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [8]:
df.isnull().count()

Serial No.           400
GRE Score            400
TOEFL Score          400
University Rating    400
SOP                  400
LOR                  400
CGPA                 400
Research             400
Chance of Admit      400
dtype: int64

In [9]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [10]:
df = df.rename(columns={'Serial No.':'id', 'GRE Score' : 'gre','TOEFL Score': 'toefl', 'University Rating':'uni_rating', 'SOP':'sop', 'LOR ':'lor', 'CGPA': 'cgpa', 'Research':'research','Chance of Admit ': 'admit_odds'})
df.head()

id  gre  toefl  uni_rating  sop  lor  cgpa  research  admit_odds
0   1  337    118           4  4.5  4.5  9.65         1        0.92
1   2  324    107           4  4.0  4.5  8.87         1        0.76
2   3  316    104           3  3.0  3.5  8.00         1        0.72
3   4  322    110           3  3.5  2.5  8.67         1        0.80
4   5  314    103           2  2.0  3.0  8.21         0        0.65

In [11]:
df['accepted'] = df['admit_odds'] > 0.74
df['accepted']= df['accepted'] == True
df.head()


id  gre  toefl  uni_rating  sop  lor  cgpa  research  admit_odds  accepted
0   1  337    118           4  4.5  4.5  9.65         1        0.92      True
1   2  324    107           4  4.0  4.5  8.87         1        0.76      True
2   3  316    104           3  3.0  3.5  8.00         1        0.72     False
3   4  322    110           3  3.5  2.5  8.67         1        0.80      True
4   5  314    103           2  2.0  3.0  8.21         0        0.65     False

In [12]:
df['accepted'] = df['accepted'].astype(int)

In [13]:
df.head()

id  gre  toefl  uni_rating  sop  lor  cgpa  research  admit_odds  accepted
0   1  337    118           4  4.5  4.5  9.65         1        0.92         1
1   2  324    107           4  4.0  4.5  8.87         1        0.76         1
2   3  316    104           3  3.0  3.5  8.00         1        0.72         0
3   4  322    110           3  3.5  2.5  8.67         1        0.80         1
4   5  314    103           2  2.0  3.0  8.21         0        0.65         0

In [14]:
y = df['accepted']
#

In [15]:
df1 = df.drop(['accepted'], axis=1)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df1, y, test_size=0.2)

In [17]:
ranfor = RandomForestClassifier(n_jobs=2, random_state=0)
ranfor.fit(X_train, y_train)

/Users/christianfreeman/anaconda3/envs/thinkful2/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [18]:
predictions=ranfor.predict(X_test)

In [19]:
ranfor.predict_proba(X_test)[10:20]

array([[0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [0.9, 0.1],
       [0.9, 0.1],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ]])

In [20]:
predictions

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1])

In [21]:
y_test

289    1
196    0
266    0
136    1
364    1
357    0
8      0
193    1
123    0
71     1
130    1
118    0
383    0
198    0
200    0
227    0
237    1
260    1
354    0
226    0
39     0
280    0
319    1
265    0
134    1
286    1
138    1
64     0
79     0
305    0
      ..
345    0
27     0
341    1
74     0
333    0
86     0
387    0
390    0
197    0
395    1
182    0
179    0
111    0
308    0
372    1
326    0
244    0
215    1
277    0
62     0
167    0
70     1
87     0
336    0
183    1
328    1
15     0
240    0
217    1
361    1
Name: accepted, Length: 80, dtype: int64

In [22]:
pd.crosstab(y_test, predictions)

col_0      0   1
accepted        
0         51   0
1          0  29

In [23]:
confusion_matrix(y_test,predictions)

array([[51,  0],
       [ 0, 29]])

In [24]:
accuracy_score(y_test, predictions, normalize=True)

1.0

In [25]:
from sklearn import tree

In [26]:
dectree = tree.DecisionTreeClassifier()

In [27]:
dectree.fit(X_train, y_train )

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [28]:
dectree.predict(X_test)

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1])

In [29]:
from sklearn.neural_network import MLPClassifier

In [30]:
mlp = MLPClassifier(hidden_layer_sizes=(100, ), activation= 'relu')


In [31]:
mlp.fit(X_train, y_train)

/Users/christianfreeman/anaconda3/envs/thinkful2/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [33]:
fashion_train = pd.read_csv('fashion-mnist_train.csv')
fashion_test = pd.read_csv('fashion-mnist_test.csv')

In [34]:
fashion_train.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [36]:
from sklearn import preprocessing
fashion_train_2 = preprocessing.scale(fashion_train)
fashion_test_2 = preprocessing.scale(fashion_test)

In [41]:
from sklearn.neural_network import BernoulliRBM

In [45]:
RBM =  BernoulliRBM(n_components=256, learning_rate=0.1, batch_size=600, n_iter=10, verbose=0, random_state=101)

In [48]:
fashion_RBM = RBM.fit(fashion_train_2)
fashion_RBM.head()

AttributeError: 'BernoulliRBM' object has no attribute 'head'

In [51]:
fashion_RBM

BernoulliRBM(batch_size=600, learning_rate=0.1, n_components=256, n_iter=10,
             random_state=101, verbose=0)