In [9]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import scipy
%matplotlib inline
from sklearn.neighbors import KNeighborsClassifier
from scipy import stats

In [3]:
df= pd.read_csv('Admission_Predict.csv')


In [4]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [4]:
df.isnull().count()

Serial No.           400
GRE Score            400
TOEFL Score          400
University Rating    400
SOP                  400
LOR                  400
CGPA                 400
Research             400
Chance of Admit      400
dtype: int64

In [5]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [10]:
df = df.rename(columns={'Serial No.':'id', 'GRE Score' : 'gre','TOEFL Score': 'toefl', 'University Rating':'uni_rating', 'SOP':'sop', 'LOR ':'lor', 'CGPA': 'cgpa', 'Research':'research','Chance of Admit ': 'admit_odds'})
df.head()

id  gre  toefl  uni_rating  sop  lor  cgpa  research  admit_odds
0   1  337    118           4  4.5  4.5  9.65         1        0.92
1   2  324    107           4  4.0  4.5  8.87         1        0.76
2   3  316    104           3  3.0  3.5  8.00         1        0.72
3   4  322    110           3  3.5  2.5  8.67         1        0.80
4   5  314    103           2  2.0  3.0  8.21         0        0.65

In [11]:
df['accepted'] = df['admit_odds'] > 0.74
df['accepted']= df['accepted'] == True
df.head()


id  gre  toefl  uni_rating  sop  lor  cgpa  research  admit_odds  accepted
0   1  337    118           4  4.5  4.5  9.65         1        0.92      True
1   2  324    107           4  4.0  4.5  8.87         1        0.76      True
2   3  316    104           3  3.0  3.5  8.00         1        0.72     False
3   4  322    110           3  3.5  2.5  8.67         1        0.80      True
4   5  314    103           2  2.0  3.0  8.21         0        0.65     False

In [12]:
df['accepted'] = df['accepted'].astype(int)

In [13]:
df.head()

id  gre  toefl  uni_rating  sop  lor  cgpa  research  admit_odds  accepted
0   1  337    118           4  4.5  4.5  9.65         1        0.92         1
1   2  324    107           4  4.0  4.5  8.87         1        0.76         1
2   3  316    104           3  3.0  3.5  8.00         1        0.72         0
3   4  322    110           3  3.5  2.5  8.67         1        0.80         1
4   5  314    103           2  2.0  3.0  8.21         0        0.65         0

In [15]:
y = df['accepted']
#

In [20]:
df1 = df.drop(['accepted'], axis=1)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df1, y, test_size=0.2)

In [24]:
ranfor = RandomForestClassifier(n_jobs=2, random_state=0)
ranfor.fit(X_train, y_train)

/Users/christianfreeman/anaconda3/envs/thinkful2/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [28]:
predictions=ranfor.predict(X_test)

In [27]:
ranfor.predict_proba(X_test)[10:20]

array([[0. , 1. ],
       [0.8, 0.2],
       [0.9, 0.1],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ]])

In [29]:
predictions

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [30]:
y_test

10     0
214    1
247    0
146    1
243    1
130    1
59     0
104    0
53     0
261    0
356    1
4      0
113    0
27     0
126    1
46     1
210    1
178    0
122    0
114    0
272    0
75     0
58     0
55     0
204    0
295    0
129    1
240    0
21     0
267    0
      ..
123    0
2      0
399    1
109    0
62     0
127    1
173    1
162    0
108    1
375    0
9      0
242    0
307    1
154    1
366    0
60     0
150    1
292    0
177    1
198    0
340    1
11     1
291    0
73     1
96     0
163    0
396    1
31     0
133    1
236    1
Name: accepted, Length: 80, dtype: int64

In [31]:
pd.crosstab(y_test, predictions)

col_0      0   1
accepted        
0         45   0
1          0  35

In [32]:
confusion_matrix(y_test,predictions)

array([[45,  0],
       [ 0, 35]])

In [33]:
accuracy_score(y_test, predictions, normalize=True)

1.0

In [34]:
from sklearn import tree

In [35]:
dectree = tree.DecisionTreeClassifier()

In [36]:
dectree.fit(X_train, y_train )

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [37]:
dectree.predict(X_test)

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [38]:
y_test

10     0
214    1
247    0
146    1
243    1
130    1
59     0
104    0
53     0
261    0
356    1
4      0
113    0
27     0
126    1
46     1
210    1
178    0
122    0
114    0
272    0
75     0
58     0
55     0
204    0
295    0
129    1
240    0
21     0
267    0
      ..
123    0
2      0
399    1
109    0
62     0
127    1
173    1
162    0
108    1
375    0
9      0
242    0
307    1
154    1
366    0
60     0
150    1
292    0
177    1
198    0
340    1
11     1
291    0
73     1
96     0
163    0
396    1
31     0
133    1
236    1
Name: accepted, Length: 80, dtype: int64

In [40]:
import time


In [42]:
start_time = time.time()

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0007760524749755859 seconds ---
